### ISSUE TITLE
variable type issues

### ISSUE THREAD

**Issue by lc525** [cadets/freebsd-old#146]
On commit 01735d95960 running the following minimal script produces dtrace errors:

```
*:syscall:::entry {
  self -> ts = timestamp;
}

*:syscall:::return/self->ts/ {
 @[probefunc] = quantize(timestamp - self->ts);
 self->ts = 0;
}

```

First, if run as above, dtrace returns with `in predicate: predicate result must be of scalar type`. If I further change the predicate to be `/self->ts!=0/` then the error becomes `quantize( ) argument #1 must be of scalar type`.

This suggests there's something wrong with the assignment of types to `self->ts`

**Comment by dstolfa** [comment]
I can't seem to reproduce this on HEAD. Could you confirm it's still a problem?

**Comment by lc525** [comment]
Indeed, no longer able to reproduce this on current HEAD ( f287a2c )

**Comment by lc525** [comment]
A variant of this happens again for 45b0a61

It does get triggered on probes of the form `host_name:syscall:::entry` but everything works just fine for probes of the type `syscall:::entry`

Minimal script to reproduce:
```
#!/usr/sbin/dtrace -Es

scylla4-nfs-experiments-vm-0:syscall:::entry
{
  self->ts = timestamp;
}

 
scylla4-nfs-experiments-vm-0:syscall:::return
/self->ts != 0/
{
  @[probefunc] = quantize(timestamp - self->ts);
	self->ts = 0;
}
```

**Comment by dstolfa** [comment]
GitHub issue tracking is not very good. The commit says **partially fixes**, not fixes. Reopening.

**Comment by dstolfa** [comment]
This is now related to #124.
